version: '3'

services:
  php_signing:
    container_name: php_signing
    build:
      context: .
      dockerfile: ./dockerfiles/php/Dockerfile
    ports:
    - 6001:6001
    expose:
      - 9000
    volumes:
      - ../signing-app:/var/www/html/signingapp:rw
      - ../landing-wellsail:/var/www/html/landing-wellsail:rw
      - ./dockerfiles/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    depends_on:
      - mysql_signing
    networks:
      - front-tier
      - back-tier

  mysql_signing:
    build:
      context: .
      dockerfile: ./dockerfiles/mysql/Dockerfile
    container_name: mysql_signing
    environment:
      MYSQL_DATABASE: signing
      MYSQL_USER: signing
      MYSQL_PASSWORD: signing
      MYSQL_ROOT_PASSWORD: signing
    ports:
      - 3308:3306
    networks:
      - back-tier

  nginx_signing:
    image: nginx:latest
    container_name: nginx_signing
    ports:
      - 8002:80
    volumes:
      - ../signing-app:/var/www/html/signingapp:rw
      - ../landing-wellsail:/var/www/html/landing-wellsail:rw
      - ./nginx:/etc/nginx/conf.d/
    networks:
      - back-tier
      - front-tier

  redis-dev:
    image: redis:latest
    container_name: redis_signing
    hostname: redis_signing
    ports:
      - 6378:6379
    networks:
      - back-tier
      - front-tier

networks:
  front-tier:
    driver: bridge
  back-tier:
    driver: bridge

volumes:
  php_signing:
  mysql_signing:
